import json
import os

notebook_path = r"c:\Users\fpabl\Documents\GITHUBS\Practica_3_imagenes-1\MorphologicalSnakesVEstudiantes.ipynb"

# New cells to append
new_cells = [
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### Implementación de Métricas de Evaluación\n",
     "\n",
     "A continuación, definimos las funciones para calcular la Sensibilidad, Especificidad y Precisión Global, tal como se solicita."
    ]
   },
   {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
     "def calculate_metrics(prediction, ground_truth):\n",
     "    \"\"\"\n",
     "    Calcula Sensibilidad, Especificidad y Precisión Global.\n",
     "    prediction: Imagen segmentada (binaria 0 y 1)\n",
     "    ground_truth: Máscara real (binaria 0 y 1)\n",
     "    \"\"\"\n",
     "    # Asegurar que son booleanos o 0/1\n",
     "    pred = prediction > 0\n",
     "    gt = ground_truth > 0\n",
     "    \n",
     "    TP = np.sum(pred & gt)\n",
     "    TN = np.sum((~pred) & (~gt))\n",
     "    FP = np.sum(pred & (~gt))\n",
     "    FN = np.sum((~pred) & gt)\n",
     "    \n",
     "    sensitivity = TP / (TP + FN) if (TP + FN) > 0 else 0\n",
     "    specificity = TN / (TN + FP) if (TN + FP) > 0 else 0\n",
     "    accuracy = (TP + TN) / (TP + TN + FP + FN) if (TP + TN + FP + FN) > 0 else 0\n",
     "    \n",
     "    return sensitivity, specificity, accuracy\n",
     "\n",
     "def load_image_gray(path):\n",
     "    img = imread(path)\n",
     "    if len(img.shape) > 2:\n",
     "        img = rgb2gray(img)\n",
     "    return img\n",
     "\n",
     "def load_mask(path, target_shape):\n",
     "    mask = imread(path)\n",
     "    if len(mask.shape) > 2:\n",
     "        mask = rgb2gray(mask)\n",
     "    # Binarizar\n",
     "    mask = mask > 0\n",
     "    # Redimensionar si es necesario (aunque idealmente deberían coincidir)\n",
     "    if mask.shape != target_shape:\n",
     "        from skimage.transform import resize\n",
     "        mask = resize(mask, target_shape, order=0, preserve_range=True, anti_aliasing=False)\n",
     "    return mask.astype(np.int8)"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### Segmentación y Evaluación de Imágenes\n",
     "\n",
     "Procesamos las imágenes solicitadas: Lagos, Estrella y Ecografía (Mama). Compararemos con las máscaras disponibles."
    ]
   },
   {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
     "# Configuración de imágenes y máscaras\n",
     "images_info = [\n",
     "    {\n",
     "        \"name\": \"Lagos\",\n",
     "        \"path\": \"images/lakes3.jpg\",\n",
     "        \"mask_path\": \"images/Mascara Lagos .png\",\n",
     "        \"method\": \"ACWE\", # Active Contours Without Edges (bueno para color/regiones)\n",
     "        \"params\": {\"iterations\": 100, \"smoothing\": 1, \"lambda1\": 1, \"lambda2\": 1}\n",
     "    },\n",
     "    {\n",
     "        \"name\": \"Estrella\",\n",
     "        \"path\": \"images/seastar2.png\",\n",
     "        \"mask_path\": \"images/Mascara Estrella.png\",\n",
     "        \"method\": \"ACWE\",\n",
     "        \"params\": {\"iterations\": 100, \"smoothing\": 1, \"lambda1\": 1, \"lambda2\": 1}\n",
     "    },\n",
     "    {\n",
     "        \"name\": \"Ecografía\",\n",
     "        \"path\": \"images/mama07ORI.bmp\",\n",
     "        \"mask_path\": None, # No encontrada, se intentará cargar si existe o se saltará evaluación\n",
     "        \"method\": \"GAC\", # Geodesic Active Contours (bueno para bordes)\n",
     "        \"params\": {\"iterations\": 100, \"smoothing\": 1, \"threshold\": 'auto', \"balloon\": -1, \"alpha\": 100, \"sigma\": 5}\n",
     "    }\n",
     "]\n",
     "\n",
     "results = []\n",
     "\n",
     "for info in images_info:\n",
     "    print(f\"Procesando {info['name']}...\")\n",
     "    \n",
     "    # Cargar imagen\n",
     "    try:\n",
     "        img = load_image_gray(info['path'])\n",
     "    except FileNotFoundError:\n",
     "        print(f\"  Error: Imagen no encontrada en {info['path']}\")\n",
     "        continue\n",
     "        \n",
     "    # Segmentación\n",
     "    if info['method'] == \"ACWE\":\n",
     "        # Morphological Chan-Vese\n",
     "        # Inicialización checkerboard por defecto\n",
     "        seg = ms.morphological_chan_vese(img, **info['params'])\n",
     "        \n",
     "    elif info['method'] == \"GAC\":\n",
     "        # Morphological Geodesic Active Contours\n",
     "        # Preprocesamiento (Inverse Gaussian Gradient)\n",
     "        alpha = info['params'].pop('alpha', 100)\n",
     "        sigma = info['params'].pop('sigma', 5)\n",
     "        gimg = ms.inverse_gaussian_gradient(img, alpha=alpha, sigma=sigma)\n",
     "        \n",
     "        # Inicialización círculo por defecto (puede requerir ajuste)\n",
     "        init_ls = ms.circle_level_set(img.shape)\n",
     "        seg = ms.morphological_geodesic_active_contour(gimg, init_level_set=init_ls, **info['params'])\n",
     "        \n",
     "    # Evaluación (si hay máscara)\n",
     "    metrics = None\n",
     "    mask = None\n",
     "    if info['mask_path']:\n",
     "        try:\n",
     "            mask = load_mask(info['mask_path'], img.shape)\n",
     "            metrics = calculate_metrics(seg, mask)\n",
     "            print(f\"  Sensibilidad: {metrics[0]:.4f}, Especificidad: {metrics[1]:.4f}, Precisión: {metrics[2]:.4f}\")\n",
     "        except FileNotFoundError:\n",
     "            print(f\"  Aviso: Máscara no encontrada en {info['mask_path']}\")\n",
     "    \n",
     "    results.append({\n",
     "        \"name\": info['name'],\n",
     "        \"image\": img,\n",
     "        \"segmentation\": seg,\n",
     "        \"mask\": mask,\n",
     "        \"metrics\": metrics\n",
     "    })\n",
     "\n",
     "# Visualización\n",
     "fig, axes = plt.subplots(len(results), 4, figsize=(20, 5 * len(results)))\n",
     "if len(results) == 1: axes = [axes]\n",
     "\n",
     "for i, res in enumerate(results):\n",
     "    # Imagen Original\n",
     "    axes[i][0].imshow(res['image'], cmap='gray')\n",
     "    axes[i][0].set_title(f\"{res['name']} Original\")\n",
     "    axes[i][0].axis('off')\n",
     "    \n",
     "    # Segmentación\n",
     "    axes[i][1].imshow(res['segmentation'], cmap='gray')\n",
     "    axes[i][1].set_title(f\"Segmentación\")\n",
     "    axes[i][1].axis('off')\n",
     "    \n",
     "    # Máscara (si existe)\n",
     "    if res['mask'] is not None:\n",
     "        axes[i][2].imshow(res['mask'], cmap='gray')\n",
     "        axes[i][2].set_title(\"Máscara Real\")\n",
     "        \n",
     "        # Comparativa (Superposición)\n",
     "        # Verde: TP, Rojo: FP, Azul: FN (aprox)\n",
     "        comp = np.zeros((*res['image'].shape, 3))\n",
     "        comp[..., 1] = res['segmentation'] # Verde predicción\n",
     "        comp[..., 0] = res['mask'] # Rojo verdad\n",
     "        # Amarillo (R+V) = TP\n",
     "        # Verde solo = FP\n",
     "        # Rojo solo = FN\n",
     "        axes[i][3].imshow(comp)\n",
     "        axes[i][3].set_title(f\"Comparativa (Amarillo=TP)\")\n",
     "    else:\n",
     "        axes[i][2].text(0.5, 0.5, \"Sin Máscara\", ha='center')\n",
     "        axes[i][3].text(0.5, 0.5, \"N/A\", ha='center')\n",
     "        \n",
     "    axes[i][2].axis('off')\n",
     "    axes[i][3].axis('off')\n",
     "\n",
     "plt.tight_layout()\n",
     "plt.show()"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### Estudio de Variación de Parámetros (Alfa y Beta)\n",
     "\n",
     "Investigamos el efecto de variar `alpha` (inverso de magnitud de gradiente) y `sigma` (suavizado gaussiano) en el método GAC para la imagen de Ecografía (o Lagos si se prefiere GAC). Asumimos que \"alfa\" y \"beta\" se refieren a estos parámetros de preprocesamiento."
    ]
   },
   {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
     "# Estudio sobre Ecografía (usando GAC)\n",
     "# Nota: Si no hay máscara real, no podemos calcular métricas cuantitativas exactas,\n",
     "# pero mostraremos los resultados visuales o usaremos una máscara generada manualmente si estuviera disponible.\n",
     "# Para este ejemplo, usaremos 'Lagos' con GAC para tener métricas, ya que tenemos su máscara.\n",
     "\n",
     "target_img_name = \"Lagos\"\n",
     "target_info = next((item for item in images_info if item[\"name\"] == target_img_name), None)\n",
     "\n",
     "if target_info and target_info['mask_path']:\n",
     "    img = load_image_gray(target_info['path'])\n",
     "    mask = load_mask(target_info['mask_path'], img.shape)\n",
     "    \n",
     "    alphas = [100, 500, 1000]\n",
     "    sigmas = [1, 3, 5]\n",
     "    \n",
     "    print(f\"Estudio de variación para {target_img_name} (Método GAC)...\")\n",
     "    print(f\"{'Alpha':<10} {'Sigma':<10} {'Sensibilidad':<15} {'Especificidad':<15} {'Precisión':<15}\")\n",
     "    \n",
     "    study_results = []\n",
     "    \n",
     "    for a in alphas:\n",
     "        for s in sigmas:\n",
     "            # Preprocesamiento\n",
     "            gimg = ms.inverse_gaussian_gradient(img, alpha=a, sigma=s)\n",
     "            \n",
     "            # Segmentación\n",
     "            init_ls = ms.circle_level_set(img.shape)\n",
     "            seg = ms.morphological_geodesic_active_contour(gimg, iterations=100, \n",
     "                                                           init_level_set=init_ls,\n",
     "                                                           smoothing=1, threshold='auto',\n",
     "                                                           balloon=-1)\n",
     "            \n",
     "            # Métricas\n",
     "            sens, spec, acc = calculate_metrics(seg, mask)\n",
     "            print(f\"{a:<10} {s:<10} {sens:<15.4f} {spec:<15.4f} {acc:<15.4f}\")\n",
     "            \n",
     "            study_results.append((a, s, seg, sens, spec, acc))\n",
     "            \n",
     "    # Visualización de algunos resultados del estudio\n",
     "    fig, axes = plt.subplots(len(alphas), len(sigmas), figsize=(15, 15))\n",
     "    fig.suptitle(f\"Segmentación GAC variando Alpha (filas) y Sigma (cols)\")\n",
     "    \n",
     "    idx = 0\n",
     "    for i, a in enumerate(alphas):\n",
     "        for j, s in enumerate(sigmas):\n",
     "            res = study_results[idx]\n",
     "            axes[i][j].imshow(res[2], cmap='gray')\n",
     "            axes[i][j].set_title(f\"A={a}, S={s}\\nAcc={res[5]:.2f}\")\n",
     "            axes[i][j].axis('off')\n",
     "            idx += 1\n",
     "    plt.tight_layout()\n",
     "    plt.show()\n",
     "else:\n",
     "    print(f\"No se pudo realizar el estudio: falta imagen o máscara para {target_img_name}\")"
    ]
   }
]

try:
    with open(notebook_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)
    
    nb['cells'].extend(new_cells)
    
    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
        
    print("Notebook updated successfully.")
except Exception as e:
    print(f"Error updating notebook: {e}")
